
export const USER_LOGIN = 'USER_LOGIN';
export const FETCH_MY_MUSIC_LIST = 'FETCH_MY_MUSIC_LIST';
export const FETCH_RECOMMEND_MUSIC_LIST = 'FETCH_RECOMMEND_MUSIC_LIST';
export const SET_SINGLE_SELECTED_MUSIC_ID = 'SET_SINGLE_SELECTED_MUSIC_ID';
export const SET_MULTIPLE_SELECTED_MUSIC_IDS = 'SET_MULTIPLE_SELECTED_MUSIC_IDS';
export const CHANGE_TO_MULTIPLE_SELECT = 'CHANGE_TO_MULTIPLE_SELECT';
export const CHANGE_TO_SINGLE_SELECT = 'CHANGE_TO_SINGLE_SELECT';

export const RENAME_MUSIC = 'RENAME_MUSIC';
export const DELETE_MUSIC = 'DELETE_MUSIC';
export const PLAY_MUSIC = 'PLAY_MUSIC';
export const SHARE_MUSIC = 'SHARE_MUSIC';
export const SLICE_MUSIC = 'SLICE_MUSIC';

export const CLOSE_AUDIOBAR = 'CLOSE_AUDIOBAR';

export const SET_AUDIO_DATA = 'SET_AUDIO_DATA';

export const SET_CURRENT_TOOL = 'SET_CURRENT_TOOL';

export const CLEAR_SLICE_MUSIC = 'CLEAR_SLICE_MUSIC';
